# Generated by Django 4.1 on 2022-09-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='short_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qisqa matn'),
        ),
    ]
