# Generated by Django 4.1 on 2022-09-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_posts_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='category',
            new_name='caegory',
        ),
    ]
