# Generated by Django 4.1 on 2022-09-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_rename_category_posts_caegory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='caegory',
            new_name='category',
        ),
    ]
