# Generated by Django 4.1 on 2022-09-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_rename_caegory_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
