# Generated by Django 4.1 on 2022-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_posts_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='taglar', to='posts.tag'),
        ),
    ]
