# Generated by Django 4.1 on 2022-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
