# Generated by Django 4.1 on 2022-10-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_posts_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='view',
            new_name='views',
        ),
    ]
