# Generated by Django 4.1 on 2022-10-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_rename_view_posts_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-id']},
        ),
    ]
