# Generated by Django 4.1 on 2022-10-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_posts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='audio',
            field=models.FileField(blank=True, upload_to='music', verbose_name='audi'),
        ),
    ]
