# Generated by Django 4.1 on 2022-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_posts_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='url',
            field=models.URLField(blank=True, max_length=150, verbose_name='url'),
        ),
    ]
