# Generated by Django 4.1 on 2022-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_posts_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='video',
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='image'),
        ),
    ]
