# Generated by Django 4.1 on 2022-10-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_remove_posts_url_posts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.TextField(),
        ),
    ]
