# Generated by Django 4.1 on 2022-10-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_posts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='posts.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Tag nomi'),
        ),
    ]
