# Generated by Django 4.1 on 2022-10-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_alter_posts_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.TextField(blank=True),
        ),
    ]
