# Generated by Django 4.1 on 2022-11-01 16:47

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_posts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
