# Generated by Django 4.1.3 on 2022-11-08 17:43

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_alter_posts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
