# Generated by Django 4.1.3 on 2022-11-20 00:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_alter_posts_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Xabar'),
        ),
    ]
