# Generated by Django 4.1.3 on 2022-12-06 01:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_alter_posts_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='posts',
            name='text_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='posts',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
