# Generated by Django 4.1.3 on 2022-12-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_category_title_en_category_title_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ism')),
                ('image', models.ImageField(upload_to='team_image')),
                ('professional', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
