# Generated by Django 4.1.3 on 2022-12-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_team_remove_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='short_text',
            new_name='quote',
        ),
    ]
